[package]
name = "otphub"
version = "1.0.10"
description = "OTP application"
authors = ["Anton Kudris"]
edition = "2021"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.10.3", features = [ "macos-private-api"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-os = "2.3.2"
tauri-plugin-clipboard-manager = "2.3.2"
tauri-plugin-process = "2.3.1"
tauri-plugin-barcode-scanner = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-mcp-bridge = "0.10"
tauri-plugin-store = "2"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = "2.4.1"

[lib]
name = "otphub_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
